#pragma once

#include <array>
#include "OMs.hpp"

namespace OMexamples {
    // Ringel's non-realizable uniform oriented matroid.
    // Symmetric under the permutation (0,3,6)(1,4,7)(2,5,8).
    constexpr Chirotope<3, 9> RIN9(
        "++++---" // (1,2,?)
        "+++---" // (1,3,?)
        "--+++" // (1,4,?)
        "-+++" // (1,5,?)
        "+--" // (1,6,?)
        "++" // (1,7,?)
        "+" // (1,8,9)
        "+++---" // (2,3,?)
        "--++-" // (2,4,?)
        "-++-" // (2,5,?)
        "+--" // (2,6,?)
        "++" // (2,7,?)
        "+" // (2,8,9)
        "--++-" // (3,4,?)
        "----" // (3,5,?)
        "---" // (3,6,?)
        "++" // (3,7,?)
        "+" // (3,8,9)
        "++++" // (4,5,?)
        "+++" // (4,6,?)
        "--" // (4,7,?)
        "-" // (4,8,9)
        "+++" // (5,6,?)
        "--" // (5,7,?)
        "-" // (5,8,9)
        "--" // (6,7,?)
        "-" // (6,8,9)
        "+" // (7,8,9)
    ); // This lives on line 73972.

    // The oriented matroid associated to the lines of the PAPPUS arrangement.
    // Namely `A_i=(0,i)`, `B_i=(i,0)` for `i=1,2,3`, `X_ij` is the intersection
    // of `A_iB_j` and `A_jB_i`, and we form the matrix from the (row-)normal
    // vectors of the following lines, where `[a,b,c]` corresponds to `ax+by+c=0`:
    // ```
    // [ 1, 0, 0] // A_1, A_2, A_3
    // [ 0,-1, 0] // B_1, B_2, B_3
    // [ 1, 2,-2] // A_1, B_2
    // [-2,-1, 2] // A_2, B_1
    // [ 1, 3,-3] // A_1, B_3
    // [-3,-1, 3] // A_3, B_1
    // [ 2, 3,-6] // A_2, B_3 
    // [-3,-2, 6] // A_3, B_2
    // [-1, 1, 0] // X_12, X_13, X_23
    // ```
    // Then the value of this chirotope on the triple `(a,b,c)` is the sign
    // of the determinant of the 3×3 matrix formed by the `a`th, `b`th, and
    // `c`th rows of this matrix.
    //
    // This has the obvious symmetry where we exchange `A_i` with `B_i` in the
    // row labels of the matrix.
    constexpr Chirotope<3,9> PAPPUS(
        "+-+-+-0+0+-++--0--+-++-0-++-----0-+0+-+-0--+-+--+-+-+0+-++-+-++--+--+-+--+-+0++---+0"
    );

    // The non-Pappus oriented matroid. Nearly the same as the Pappus OM
    // (see `PAPPUS`), but the line `X_12X_13` no longer passes through
    // `X_23`.
    constexpr Chirotope<3,9> NON_PAPPUS(
        "+-+-+-0+0+-++--0--+-++-0-++-----0-+0+-+-0--+-+--+-+-+0+-++-+-++--+--+-+--+-+0++---++"
    );

    // The non-realizable uniform oriented matroid RS(8). See chapter 1.5
    // and page 21 of [BSLWZ]. It is fixed under the permutations
    // (1,4)(2,3)(5,8)(6,7) and (1,7)(2,8)(3,5)(4,6) - these generate the
    // Klein group.
    constexpr Chirotope<4,8> RS8(
        "+++++++"
        "-++----"
        "+-+--++"
        "+--++--"
        "+-+++-+"
        "----+++"
        "-+++-+-"
        "++++--+"
        "----+++"
        "---+--+"
    );

    // The non-realizable uniform oriented matroid EFM(8). See example 
    // 10.4.1 and figure 10.4.5 on page 465 of [BSLWZ]. It is fixed
    // under an action of D_3 generated by the permutations
    // (1,2,3)(4,5,6) and (1,6)(2,5)(3,4)(7,8). It is also self-dual
    // up to isomorphism: after duality, apply (2,3)(4,5) and the
    // reorientation -4568 (these three operations compose to a symmetry
    // of MacP(4,8) that squares to the identity).
    constexpr Chirotope<4,8> EFM8(
        "-----+-"
        "++---++"
        "+++++--"
        "-----++"
        "+++----"
        "+++++++"
        "--+---+"
        "+-+++--"
        "-------"
        "-++++-+"
    );

    // List of all reorientation classes of non-realizable uniform oriented
    // matroids of rank 4 on 8 elements. "Reorientation class" means
    // oriented matroids can be relabelled and any element can be
    // inverted. All reorientation classes are self-dual [prop. 1.2, JB&JRG-II].
    // Source: [Appendix 2, JB&JRG-I]. See also: [Appendix, JB&JRG-II].
    //
    // - [JB&JRG-I] Jürgen Bokowski, Jürgen Richer-Gebert, On the classification of non-realizable oriented matroids Part II. Properties, 1990
    // - [JB&JRG-II] Jürgen Bokowski, Jürgen Richer-Gebert, On the classification of non-realizable oriented matroids Part I. Generation, 1990
    constexpr std::array<Chirotope<4,8>, 24> NON_REALIZABLES{
        Chirotope<4,8>("+++++--" "-------" "-++++++" "-+----+" "-++++++" "------+" "-++++-+" "-------" "++++-++" "++----+"),
        Chirotope<4,8>("+++++--" "-------" "+++++++" "++++---" "---++--" "-------" "---++++" "++--++-" "+++++++" "----++-"),

        Chirotope<4,8>("+++++--" "------+" "+++++++" "++----+" "-++++++" "---+--+" "-++++-+" "-------" "+++++++" "++-+---"),
        Chirotope<4,8>("++-+++-" "-----++" "+---+-+" "++++--+" "-------" "++-++--" "+-+++++" "+-+++++" "+-+--++" "++-----"),
        Chirotope<4,8>("--++++-" "--+++-+" "++-----" "+---+++" "+++---+" "-+++--+" "+--++-+" "++---++" "+-+++--" "-+---+-"),

        Chirotope<4,8>("++----+" "+++++--" "+-+++++" "+---+--" "++++++-" "+------" "++--++-" "-+---++" "++-++++" "+----+-"),
        Chirotope<4,8>("+-++-+-" "-+-++-+" "-+--+--" "-++++++" "-----+-" "-++--+-" "-+++--+" "-+--+-+" "-++--++" "-+--+--"),
        Chirotope<4,8>("-++--++" "---++++" "+-----+" "++++-++" "++-++++" "--+++--" "----+++" "+++++--" "+++++++" "+-++---"),

        Chirotope<4,8>("+--++--" "--+++++" "+--+-++" "+++-+-+" "--+++--" "+-+++--" "+-++---" "--+++++" "-++-+++" "-+-+--+"),
        Chirotope<4,8>("+--++--" "--+++++" "+++--+-" "-++++++" "++-++++" "+++++--" "---++-+" "--++++-" "++++-++" "+++++++"),
        Chirotope<4,8>("--+----" "-+--++-" "+---+--" "++++--+" "------+" "-+-----" "++-+---" "+----++" "-------" "-+---++"),

        Chirotope<4,8>("--++-++" "--+--+-" "++-+--+" "--+++--" "++-++-+" "+++++++" "-------" "-+--+--" "+-++-++" "-+--+++"),
        Chirotope<4,8>("-+--+-+" "-+-+--+" "+--++++" "-+++-+-" "+-+-+++" "++++--+" "-+++++-" "+++---+" "++++---" "--++--+"),
        Chirotope<4,8>("++++---" "-+++--+" "++++-++" "-+-+--+" "---+---" "+++----" "+--+-+-" "+++----" "-----+-" "---++++"),
        
        Chirotope<4,8>("++++---" "-------" "----+--" "+-+-++-" "+------" "+++-+++" "+++--++" "+++++-+" "+-+-+--" "-------"),
        Chirotope<4,8>("++++---" "-+--+-+" "----+--" "+-+-++-" "+++-+-+" "+++-++-" "+----++" "-++-+++" "+++++-+" "++---++"),
        Chirotope<4,8>("++++---" "-------" "----+--" "+-+-++-" "+------" "+++-+++" "+++--++" "+++++-+" "+-+-+--" "---+---"),

        Chirotope<4,8>("++++---" "-------" "----+--" "+---++-" "+------" "+++-++-" "+++--++" "+++++-+" "+-+-+--" "---+---"),
        Chirotope<4,8>("+++++--" "-+--+-+" "+------" "---++++" "+++-+++" "+++++++" "+-----+" "--+--++" "++++--+" "++--+++"),
        Chirotope<4,8>("-+--+++" "++---++" "++-+---" "++-++++" "-++---+" "--++++-" "++++---" "--+++++" "--++-+-" "+---++-"),
        
        Chirotope<4,8>("++++---" "-+--++-" "+---+--" "++++--+" "+-----+" "---+--+" "+---+++" "-++++--" "+++++++" "+-+++-+"),
        Chirotope<4,8>("----+++" "+---+-+" "----+-+" "-+-++--" "-+-+-++" "---+--+" "+-+++-+" "--+-+++" "-+-++-+" "--+-+++"),
        Chirotope<4,8>("----+-+" "+++++++" "+-+--++" "----+--" "++++++-" "--+-++-" "+-+----" "++-+++-" "++++--+" "--++-++"),

        Chirotope<4,8>("+++++--" "++-++++" "+-----+" "+++--++" "++-++--" "++--+--" "--++---" "-+++++-" "++++-++" "-+++-++")
    };
}